name = "Kaio-Yuuji - SGC Build"
author = "Dartis-Craft x Kaio-Yuuji"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "497fba41487dfc81456e833cf4bcb20fbb96736f4006e13f8749c2a3253acbd4"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
